using Content.Client.Consent.UI;
using Content.Client.UserInterface.Controls;
using Content.Shared.CCVar;
using Content.Shared._Common.CCVar;
using Content.Shared.Consent;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Consent.UI.Windows;

[GenerateTypedNameReferences]
public sealed partial class ConsentWindow : FancyWindow
{
    [Dependency] private readonly IClientConsentManager _consentManager = default!;
    [Dependency] private readonly IConfigurationManager _configManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    private List<ConsentToggleControl> ConsentToggles = new();

    public ConsentWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SaveConsentSettings.OnPressed += _ => {
            SaveConsentSettings.Disabled = true;
            _consentManager.UpdateConsent(GetSettings());
        };

        ConsentFreetext.Placeholder = new Rope.Leaf(Loc.GetString("consent-window-freetext-placeholder"));
        ConsentFreetext.OnTextChanged += _ => UnsavedChanges();

        foreach (var toggle in _prototypeManager.EnumeratePrototypes<ConsentTogglePrototype>())
        {
            var toggleControl = new ConsentToggleControl(toggle);
            ConsentSettings.Children.Add(toggleControl);
            toggleControl.OnStateChange += _ => UnsavedChanges();
            ConsentToggles.Add(toggleControl);
        }

        _consentManager.OnServerDataLoaded += UpdateUi;
        if (_consentManager.HasLoaded)
            UpdateUi();
    }

    private PlayerConsentSettings GetSettings()
    {
        var text = Rope.Collapse(ConsentFreetext.TextRope);
        var toggles = new Dictionary<ProtoId<ConsentTogglePrototype>, string>();

        foreach (var toggleControl in ConsentToggles)
        {
            toggles[toggleControl.ConsentToggleProtoId] = toggleControl.State;
        }

        return new(text, toggles);
    }

    private void UnsavedChanges()
    {
        // Validate freetext length
        var maxLength = _configManager.GetCVar(ConsentSystemCCVars.ConsentFreetextMaxLength);
        var length = Rope.Collapse(ConsentFreetext.TextRope).Length;

        if (length > maxLength)
        {
            SaveLabel.Text = Loc.GetString("consent-window-char-limit-warning", ("length", length), ("maxLength", maxLength));
            SaveConsentSettings.Disabled = true;

            return;
        }

        // If everything is valid, enable save button and inform user they need to save.
        SaveLabel.Text = Loc.GetString("consent-window-unsaved-changes");
        SaveConsentSettings.Disabled = false;
    }

    public void UpdateUi()
    {
        var consent = _consentManager.GetConsent();
        ConsentFreetext.TextRope = new Rope.Leaf(consent.Freetext);

        foreach (var toggleControl in ConsentToggles)
        {
            if (consent.Toggles.TryGetValue(toggleControl.ConsentToggleProtoId, out var toggle))
            {
                toggleControl.SetState(toggle);
            }
            else
            {
                toggleControl.SetState("off");
            }
        }

        SaveConsentSettings.Disabled = true;
        SaveLabel.Text = "";
    }
}
